workflows:
  flutter-workflow:
    name: Flutter workflow
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
    artifacts:
      - build/**/*
    publishing:
      email:
        recipients:
          - your.email@example.com
